# OnigiriPress Configuration Template
# Copy this file to config.yaml and customize with your information
#
# NAVIGATION CUSTOMIZATION:
# You can add unlimited custom sections under 'home.navigation' by creating new keys.
# Each section requires a 'type' field that must be one of:
# - about: For text content with optional photo
# - education: For educational background entries
# - experience: For work experience entries  
# - projects: For project showcases
# - contact: For contact information
#
# Example of adding a custom section:
# home:
#   navigation:
#     my_custom_section:
#       title: "My Custom Section"
#       icon: "🚀"
#       type: "about"
#       content: "Your content here..."

website:
  title: "Your Name"
  titleSeparator: " | "
  favicon: "/favicon.png"
  description: "Portfolio website of Your Name. Customize this description with your own information."


# Background configuration
backgrounds:
  # Global fixed background for all pages - test with external URL
  global: "https://w.wallhaven.cc/full/6l/wallhaven-6lqk2l.png"
  # Hero section background (Home page) - using local path
  hero: "https://w.wallhaven.cc/full/5y/wallhaven-5yd6d5.png"

home:
  hero:
    name: "YOUR NAME"
    quote: "Your inspiring quote or tagline here."

  profileCard:
    name: "Your Name"
    title: "Your Job Title"
    subtitle: "Your Subtitle"
    avatar: "favicon.png"  # Avatar image for profile card

  # Navigation sections configuration
  # You can add custom sections by creating new keys under 'navigation'
  # Each section must have a 'type' field that matches one of: about, education, experience, projects, contact
  # 
  # Section structure:
  # your_custom_key:
  #   title: "Section Title"     # Display title for the section
  #   icon: "🔗"                # Emoji icon for the section
  #   type: "about|education|experience|projects|contact"  # Required: determines section layout
  #   ... (additional fields based on type)
  #
  # Type-specific fields:
  # - about: content (markdown text), photo (optional image)
  # - education: items (array of education entries)
  # - experience: items (array of work experience entries)  
  # - projects: items (array of project entries), defaultCover (optional)
  # - contact: content (description), email, github, linkedin, textColor
  navigation:
    about:
        title: "About Me"
        icon: "👤"
        type: "about"
        content: >
          Write your self-introduction here. This section supports markdown formatting, 
          so you can include [links](https://example.com) and other formatting.
        photo: "onigiripress.svg"

    education:
      title: "Education"
      icon: "🎓"
      type: "education"
      items:
        - schoolName: "Your University"
          degree: "Your Degree"
          duration: "Your Duration"
          location: "Your Location"
          logo:
            src: ""
            backgroundColor: "#990000"
          border:
            color: "#990000"
            hoverColor: "#cc0000"
          highlightColor: "#990000"
          highlights:
            - "Add your achievements and coursework here"

    experience:
      title: "Experience"
      icon: "💼"
      type: "experience"
      items:
        - companyName: "Your Company"
          location: "City, Country"
          logo:
            src: "company-logo.png"
          border:
            color: "#e74d29"
            hoverColor: "#e77e29"
          highlightColor: "#e74d29"
          positions:
          - position: "Your Position"
            duration: "Your Duration"
            highlights:
            - "Describe your achievements and responsibilities"
            - "Add more bullet points as needed"
          - position: "Another Position"
            duration: "Another Duration"
            highlights:
            - "Describe your achievements and responsibilities for this position"
            - "Add more bullet points as needed"

    projects:
      title: "Projects"
      icon: "💻"
      type: "projects"
      defaultCover: "default_cover.jpg"
      items:
        - projectName: "Your Project Name"
          description: "Brief description of your project"
          tag:
            items: ["Technology1", "Technology2", "Technology3"]
          duration: "Project Duration"
          projectLink:
            url: "https://your-project-url.com"
            textColor: ""
          githubLink:
            url: "https://github.com/yourusername/your-repo"
            textColor: ""
            backgroundColor: "#2c3e50"
          highlights:
            - "Key feature or achievement 1"
            - "Key feature or achievement 2"

        - projectName: "Weather Analytics Dashboard"
          description: "An interactive dashboard for weather data visualization and climate trend analysis"
          tag:
            items: ["Python", "D3.js", "Flask", "OpenWeather API"]
            backgroundColor: "#eff6ff"
            textColor: "#1d4ed8"
          duration: "Mar 2023 - Jul 2023"
          projectLink:
            url: "https://example.com/weather-dashboard"
            textColor: ""
          githubLink:
            url: "https://github.com"
            backgroundColor: "#1e40af"
            textColor: "#ffffff"
          coverImage: "default_cover.jpg"
          border:
            color: "#2563eb"
            hoverColor: "#1d4ed8"
          highlightColor: "#2563eb"
          highlights:
            - "Interactive charts with D3.js for data visualization"
            - "Historical weather data analysis and trend prediction"
            - "RESTful API integration with multiple weather services"
            - "Responsive design with data export functionality"

        - projectName: "AI Chat Assistant"
          description: "An intelligent chatbot with natural language processing and context awareness"
          tag:
            items: ["Python", "OpenAI API", "FastAPI", "React"]
            backgroundColor: "#fef3c7"
            textColor: "#d97706"
          duration: "Sep 2023 - Nov 2023"
          projectLink:
            url: ""
            textColor: "#ffffff"
          githubLink:
            url: "https://github.com"
            backgroundColor: "#ea580c"
            textColor: "#ffffff"
          coverImage: "default_cover.jpg"
          border:
            color: "#f59e0b"
            hoverColor: "#d97706"
          highlightColor: "#f59e0b"
          highlights:
            - "Context-aware conversations with memory management"
            - "Custom training on domain-specific knowledge"
            - "Multi-language support and sentiment analysis"
            - "Integration with popular messaging platforms"

    # Example contact section - you can add multiple contact sections if needed
    contact:
      title: "Get In Touch"
      icon: "📬"
      type: "contact"  # Required: must be 'contact' for contact sections
      content: "Feel free to reach out for collaborations, opportunities, or just to say hello!"
      email: "your.email@example.com"
      github: "https://github.com/yourusername"
      linkedin: "https://www.linkedin.com/in/yourprofile"
      textColor: "#2958e7"  # Color for contact links and icons

    # Example: Add a custom section (uncomment and customize)
    # skills:
    #   title: "Technical Skills"
    #   icon: "⚡"
    #   type: "about"  # Uses 'about' type for simple content display
    #   content: >
    #     **Programming Languages:** JavaScript, Python, TypeScript, Java
    #     
    #     **Frameworks:** React, Node.js, Django, Express.js
    #     
    #     **Tools:** Git, Docker, AWS, MongoDB, PostgreSQL

# Navigation bar configuration
navbar:
  showHome: true
  showCV: true
  showProjects: true
  showBlogs: true
  showLogs: false
  showArchive: true

# Content display settings
content:
  blogs:
    defaultCover: "default_cover.jpg"
    defaultHeaderBackground: "background/default_blog.png"
  projects:
    defaultCover: "default_cover.jpg"
    defaultHeaderBackground: "background/default_proj.jpg"
  archive:
    defaultCover: "default_cover.jpg"
    defaultHeaderBackground: "background/default_blog.png"
  logs:
    defaultHeaderBackground: "background/default_blog.png"
  
  # Global category colors (shared across blogs, projects, and archive)
  # Each category only uses textColor for the text display
  categoryColors:
    default: # Default fallback for all unspecified categories
      textColor: "#5a0cea"
    "Full Stack": 
      textColor: "#059669"
    "Frontend":
      textColor: "#3b82f6"
    "Backend":
      textColor: "#8b5cf6"
    "Machine Learning":
      textColor: "#f59e0b"
    "Research":
      textColor: "#ef4444"
    "Web Development":
      textColor: "#10b981"
    "Mobile Development":
      textColor: "#f97316"
    "Data Science":
      textColor: "#8b5cf6"
    "Computer Vision":
      textColor: "#06b6d4"
    "Tutorial":
      textColor: "#3b82f6"
    "Technology":
      textColor: "#6366f1"
    "Personal":
      textColor: "#ec4899"
    "Documentation":
      textColor: "#f43f5e"

  # Global tag colors (shared across blogs, projects, and archive)  
  # Each tag uses both backgroundColor and textColor
  tagColors:
    default: # Default fallback for all unspecified tags
      backgroundColor: "#f3f4f6"
      textColor: "#374151"
    "React":
      backgroundColor: "#dbeafe" 
      textColor: "#1d4ed8"
    "TypeScript":
      backgroundColor: "#eff6ff"
      textColor: "#2563eb"
    "JavaScript":
      backgroundColor: "#fef3c7"
      textColor: "#d97706"
    "Python":
      backgroundColor: "#dcfce7"
      textColor: "#16a34a"
    "Node.js":
      backgroundColor: "#dcfce7"
      textColor: "#059669"
    "Django":
      backgroundColor: "#dcfce7"
      textColor: "#16a34a"
    "Express":
      backgroundColor: "#f3f4f6"
      textColor: "#374151"
    "MongoDB":
      backgroundColor: "#dcfce7"
      textColor: "#059669"
    "PostgreSQL":
      backgroundColor: "#dbeafe"
      textColor: "#1d4ed8"
    "CSS Modules":
      backgroundColor: "#fce7f3"
      textColor: "#be185d"
    "Vite":
      backgroundColor: "#fef3c7"
      textColor: "#d97706"
    "PyTorch":
      backgroundColor: "#fee2e2"
      textColor: "#dc2626"
    "OpenCV":
      backgroundColor: "#dbeafe"
      textColor: "#1d4ed8"
    "Blender":
      backgroundColor: "#fef3c7"
      textColor: "#d97706"
    "OpenAI API":
      backgroundColor: "#f0fdf4"
      textColor: "#16a34a"
    "MQTT":
      backgroundColor: "#f3f4f6"
      textColor: "#374151"
    "D3.js":
      backgroundColor: "#fef3c7"
      textColor: "#d97706"
    "Swift":
      backgroundColor: "#fee2e2"
      textColor: "#dc2626"
    "ARKit":
      backgroundColor: "#fee2e2"
      textColor: "#dc2626"
    "CoreLocation":
      backgroundColor: "#f3f4f6"
      textColor: "#374151"
    "MapKit":
      backgroundColor: "#f0fdf4"
      textColor: "#16a34a"
    "Firebase":
      backgroundColor: "#fef3c7"
      textColor: "#d97706"
    "Markdown":
      backgroundColor: "#1f2937"
      textColor: "#f3f4f6"

resume:
  filename: "Your_Resume.pdf"

# Footer configuration
footer:
  copyright: "© 2025 by Your Name. All rights reserved."
  message: "Welcome to my portfolio website!"
  background: "/background/hero.jpg"  # Footer background image - can be local path or URL

# Audio Player configuration
audioPlayer:
  enabled: false   # Set to true to enable audio player
  fixed: true   # Set to true for floating player
  volume: 0.7
  showLrc: true
  
  # MetingJS configuration
  meting:
    enabled: false   # Set to true to use MetingJS instead of local audio files
    server: "netease"   # Music server: netease, tencent, kugou, xiami, baidu
    type: "playlist"    # Type: song, playlist, album, search, artist
    id: "your-playlist-id"    # Music ID from the platform
    mutex: true         # Prevent multiple players from playing simultaneously
    listFolded: false   # Whether to fold the playlist
    listMaxHeight: "340px"  # Maximum height of the playlist
    order: "random"       # Play order: list, random
    loop: "all"         # Loop mode: all, one, none
    preload: "auto"     # Preload: auto, metadata, none
    
  # Local audio files (used when meting.enabled is false)
  audio:
    - name: "Your Song Title"
      artist: "Artist Name"
      url: ""
      cover: "/background/hero.jpg"
